export const reducerCases = {
  SET_ALL_SKILLS: 'SET_ALL_SKILLS',
  SET_EMPLOYEE_SKILLS: 'SET_EMPLOYEE_SKILLS',
  SET_USER: 'SET_USER',
  SET_EMPLOYEE_PROFILE: 'SET_EMPLOYEE_PROFILE',
  SET_FILTERED_SKILLS: 'SET_FILTERED_SKILLS',
};
